sylius_grid:
    grids:
        app_admin_subcontractor:
            driver:
                options:
                    class: '%app.model.subcontractor.class%'
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                email:
                    type: string
                    label: sylius.ui.email
                taxons:
                    type: string
                    label: sylius.ui.taxons
                    path: countTaxons
                state:
                    type: twig
                    label: sylius.ui.state
                    options:
                        template: 'Subcontractor/Grid/_state.html.twig'
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    validate:
                        type: apply_transition
                        label: app.ui.validate
                        icon: star
                        options:
                            link:
                                route: app_admin_subcontractor_validate
                                parameters:
                                    id: resource.id
                            graph: app_subcontractor
                            transition: validate
                            class: yellow
