sylius_grid:
    grids:
        app_admin_subcontractor:
            driver:
                options:
                    class: '%app.model.subcontractor.class%'
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                email:
                    type: string
                    label: sylius.ui.email
                state:
                    type: twig
                    label: sylius.ui.state
                    options:
                        template: 'Subcontractor/Grid/_state.html.twig'
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
