sylius_grid:
    grids:
        app_admin_subcontractor:
            driver:
                options:
                    class: '%app.model.subcontractor.class%'
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                email:
                    type: string
                    label: sylius.ui.email
