sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin
    
app_subcontractor:
    resource: |
        alias: app.subcontractor
        except: ['show']
        templates: SyliusAdminBundle:Crud
        grid: app_admin_subcontractor
        section: admin
    type: sylius.resource
    prefix: /admin
