# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Context\TimeBasedChannelContext:
        tags:
            - {name: sylius.context.channel, priority: 1000}
    
    App\ShippingCalculator\WeightBasedShippingCalculator:
        tags:
            - 
                {
                    name: sylius.shipping_calculator,
                    calculator: "weight_based",
                    form_type: 'App\Form\Type\WeightBasedShippingCalculatorType',
                    label: 'app.ui.shipping_calculator.weight_based'
                }
    App\Listener\AdminMainMenuListener:
        tags:
            - {name: kernel.event_listener, event: sylius.menu.admin.main, method: addSubcontractorsMenu}

    App\Form\Type\SubcontractorType:
        arguments:
            - '%app.model.subcontractor.class%'

    App\Notifier\SubcontractorValidationNotifierInterface:
        class: App\Notifier\LogSubcontractorValidationNotifier
        arguments:
            - '@logger'
        public: true
        
    App\Fixture\SubcontractorFixture:
        arguments:
            - '@app.factory.subcontractor'
            - '@app.manager.subcontractor'
            - '@Faker\Generator'
        tags:
            - {name: sylius_fixtures.fixture}
    
    App\AttributeType\RangeAttributeType:
        tags:
            - {name: sylius.attribute.type, attribute_type: 'range', label: 'Range', form_type: App\Form\Type\RangeAttributeType}

    App\PriceCalculator\ProductVariantPriceCalculator:
        decorates: sylius.calculator.product_variant_price
        arguments:
            - '@App\PriceCalculator\ProductVariantPriceCalculator.inner'
            - '@App\Provider\UnitPriceFactorProviderInterface'
    
    sylius.order_processing.order_prices_recalculator:
        class: App\OrderProcessing\OrderPricesRecalculator
        arguments:
            - '@sylius.calculator.product_variant_price'
        tags:
            - {name: sylius.order_processor, priority: 40}

    sylius.templating.helper.price:
        class: App\Twig\Helper\PriceHelper
        arguments:
            - '@sylius.calculator.product_variant_price'
        tags:
            - {name: templating.helper, alias: 'sylius_resolve_variant'}
    
    App\Controller\OneClickCheckoutAction:
        arguments:
            - '@sylius.repository.product_variant'
            - '@sylius.factory.order'
            - '@sylius.factory.order_item'
            - '@sylius.order_item_quantity_modifier'
            - '@sylius.context.shopper'
            - '@sm.factory'
            - '@sylius.manager.order'
        public: true
